# Generated by Django 4.0.5 on 2022-07-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_mainphoto'),
    ]

    operations = [

    ]
