# Generated by Django 4.0.5 on 2022-07-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category_menu_product_category_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('uploadedFile', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='mainphoto',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
