# Generated by Django 4.0.5 on 2022-07-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_document_alter_post_mainphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='db_print_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=300)),
                ('class_name', models.CharField(max_length=200)),
                ('percent', models.CharField(max_length=200)),
            ],
        ),
    ]
