# Generated by Django 4.0.5 on 2022-07-19 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_db_print_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
